# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'bbc00546-6924-4a6f-981e-eb246a6761fb'
  imageRepository: 'mydocimage1'
  containerRegistry: 'devsecopscontainer212.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'smarthotel-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
             action: deploy
             namespace: $(k8sNamespace)
             manifests: $(System.ArtifactsDirectory)/manifests/*
             imagePullSecrets: $(imagePullSecret)
             containers: $(containerRegistry)/$(imageRepository):$(tag)
              # value for kubernetesServiceConnection input automatically passed down to task by environment.resource input